apiVersion: v1
kind: Pod
metadata: 
  name: myapp-Pod
  lables:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "taintdemo"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"