#command to store the secret
#kubectl create secret generic db-user-pass --from-file=username.txt --from-file=password.txt

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  labels:
    name: secret-env-pod
spec:
  containers:
  - name: secret-env-pod-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: Sec_username
        valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username.txt
      - name: Sec_password
        valueFrom:
            secretKeyRef:
              name: db-user-pass
              key:  password.txt
  restartPolicy: Never