
apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
  labels:
    name: volume-demo
spec:
  volumes:
    - name: storage-v
      hostPath:
          path: /data
          type: DirectoryOrCreate
  containers:
  - name: volume-demo-container
    image: jenkins/jenkins:lts
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: storage-v
        mountPath: /var/jenkins_home
