#create namespace prior to rule below definition
#kubectl create ns development

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: development
  name: read-secrets
subjects:
  - kind: User
    name: karthick
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole # This must be Role or ClusterRole
  name: secret-reader #This must match the name of the role or Clusterrole you wish to bind to.