apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubernetes-dashboard
  name: pod-reader
rules:
  - apiGroups:
    - "" # indicated the core API group
    resources:
     - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kubernetes-dashboard
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: raghavan
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # This must be Role or ClusterRole
  name: pod-reader #This must match the name of the role or Clusterrole you wish to bind to.