apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: secret-reader
rules:
  - apiGroups:
    - "" # indicated the core API group
    resources:
     - "secrets"
    verbs:
      - "get"
      - "watch"
      - "list"