apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups:
    - "" # indicated the core API group
    resources:
     - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"